name = "rks_explosions"
uid = "7749EEN4-DE86-5CC2-39AC-35672BDE76DG"
version = 6
description = "Makes explosions better looking and more optimized."
author = "RK4000, Domino, Sheeo, Gyle (advertising) and everyone else that posted feedback."
url = "FAF forums, check useful mods subthread."
selectable = true
enabled = true
exclusive = false
ui_only = false
icon = "/mods/rks_explosions/icon.jpg" 
before = {}
after = {}
