name = "rks_explosions V9 BETA"
uid = "EFFFA8C6-96D9-11E4-9DA1-432D1D5D46B0"
version = 1
description = "Non-toggle version of V9 beta made playable as per request. :)"
author = "RK4000, Sheeo, Everyone that posted feedback on the forums."
url = "FAF forums, check useful mods subthread."
selectable = true
enabled = true
exclusive = false
ui_only = false
icon = "/mods/rks_explosions/icon.jpg" 
before = {}
after = {}
conflicts = {}